# Устанавливаем необходимые зависимости:

In [2]:
!pip install -U bitsandbytes accelerate transformers trl==0.19.0 datasets peft

Collecting bitsandbytes
  Using cached bitsandbytes-0.49.2-py3-none-win_amd64.whl.metadata (10 kB)
Collecting accelerate
  Using cached accelerate-1.13.0-py3-none-any.whl.metadata (19 kB)
Collecting transformers
  Using cached transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Collecting trl==0.19.0
  Using cached trl-0.19.0-py3-none-any.whl.metadata (10 kB)
Collecting datasets
  Using cached datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Collecting peft
  Using cached peft-0.18.1-py3-none-any.whl.metadata (14 kB)
Collecting torch<3,>=2.3 (from bitsandbytes)
  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
Collecting numpy>=1.17 (from bitsandbytes)
  Using cached numpy-2.4.4-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: packaging>=20.9 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from bitsandbytes) (26.0)
Collecting filelock (from torch<3,>=2.3->bitsandbytes)
  Using cached filelock-3.25.2-py3-none-any.whl.metadata (2.0 kB)
Collecting typing-extensions>=4.10.0 (from torch<3,>=2.3->bitsandbytes)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting setuptools<82 (from torch<3,>=2.3->bitsandbytes)
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Collecting sympy>=1.13.3 (from torch<3,>=2.3->bitsandbytes)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch<3,>=2.3->bitsandbytes)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2 (from torch<3,>=2.3->bitsandbytes)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting fsspec>=0.8.5 (from torch<3,>=2.3->bitsandbytes)
  Using cached fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: psutil in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from accelerate) (7.2.2)
Collecting pyyaml (from accelerate)
  Using cached pyyaml-6.0.3-cp313-cp313-win_amd64.whl.metadata (2.4 kB)
Collecting huggingface_hub>=0.21.0 (from accelerate)
  Using cached huggingface_hub-1.9.0-py3-none-any.whl.metadata (14 kB)
Collecting safetensors>=0.4.3 (from accelerate)
  Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Collecting regex>=2025.10.22 (from transformers)
  Using cached regex-2026.4.4-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting typer (from transformers)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting tqdm>=4.27 (from transformers)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface_hub>=0.21.0->accelerate)
  Using cached hf_xet-1.4.3-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface_hub>=0.21.0->accelerate)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting anyio (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting pyarrow>=21.0.0 (from datasets)
  Using cached pyarrow-23.0.1-cp313-cp313-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Using cached pandas-3.0.2-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting requests>=2.32.2 (from datasets)
  Using cached requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting xxhash (from datasets)
  Using cached xxhash-3.6.0-cp313-cp313-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py313-none-any.whl.metadata (7.5 kB)
Collecting fsspec>=0.8.5 (from torch<3,>=2.3->bitsandbytes)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Downloading aiohttp-3.13.5-cp313-cp313-win_amd64.whl.metadata (8.4 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached frozenlist-1.8.0-cp313-cp313-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached multidict-6.7.1-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached propcache-0.4.1-cp313-cp313-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached yarl-1.23.0-cp313-cp313-win_amd64.whl.metadata (82 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets)
  Using cached charset_normalizer-3.4.7-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.32.2->datasets)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch<3,>=2.3->bitsandbytes)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Collecting MarkupSafe>=2.0 (from jinja2->torch<3,>=2.3->bitsandbytes)
  Using cached markupsafe-3.0.3-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Collecting tzdata (from pandas->datasets)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Collecting click>=8.2.1 (from typer->transformers)
  Using cached click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->transformers)
  Using cached rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->transformers)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached trl-0.19.0-py3-none-any.whl (375 kB)
Downloading bitsandbytes-0.49.2-py3-none-win_amd64.whl (55.4 MB)
   ---------------------------------------- 0.0/55.4 MB ? eta -:--:--
   ---------------------------------------- 0.5/55.4 MB 8.8 MB/s eta 0:00:07
   -- ------------------------------------- 3.1/55.4 MB 12.0 MB/s eta 0:00:05
   --- ------------------------------------ 5.5/55.4 MB 11.5 MB/s eta 0:00:05
   ---- ----------------------------------- 6.3/55.4 MB 10.1 MB/s eta 0:00:05
   ------ --------------------------------- 8.7/55.4 MB 9.6 MB/s eta 0:00:05
   ------- -------------------------------- 11.0/55.4 MB 9.8 MB/s eta 0:00:05
   --------- ------------------------------ 13.4/55.4 MB 10.0 MB/s eta 0:00:05
   ----------- ---------------------------- 16.0/55.4 MB 10.4 MB/s eta 0:00:04
   ------------- -------------------------- 18.9/55.4 MB 10.8 MB/s eta 0:00:04
   --------------- ------------------------ 21.5/55.4 MB 10.9 MB/s eta 0:00:04
   ----------------- ---------------------- 23.6/55.4 MB 10.9 MB/s eta 0:00:03
   ------------------ --------------------- 26.2/55.4 MB 11.0 MB/s eta 0:00:03
   -------------------- ------------------- 28.8/55.4 MB 11.1 MB/s eta 0:00:03
   ---------------------- ----------------- 31.5/55.4 MB 11.2 MB/s eta 0:00:03
   ------------------------ --------------- 34.1/55.4 MB 11.2 MB/s eta 0:00:02
   -------------------------- ------------- 36.2/55.4 MB 11.2 MB/s eta 0:00:02
   ---------------------------- ----------- 38.8/55.4 MB 11.3 MB/s eta 0:00:02
   ----------------------------- ---------- 41.2/55.4 MB 11.3 MB/s eta 0:00:02
   ------------------------------- -------- 43.8/55.4 MB 11.3 MB/s eta 0:00:02
   -------------------------------- ------- 45.1/55.4 MB 11.1 MB/s eta 0:00:01
   --------------------------------- ------ 46.1/55.4 MB 10.8 MB/s eta 0:00:01
   --------------------------------- ------ 46.1/55.4 MB 10.8 MB/s eta 0:00:01
   --------------------------------- ------ 46.1/55.4 MB 10.8 MB/s eta 0:00:01
   --------------------------------- ------ 46.1/55.4 MB 10.8 MB/s eta 0:00:01
   --------------------------------- ------ 46.1/55.4 MB 10.8 MB/s eta 0:00:01
   --------------------------------- ------ 46.1/55.4 MB 10.8 MB/s eta 0:00:01
   --------------------------------- ------ 46.1/55.4 MB 10.8 MB/s eta 0:00:01
   --------------------------------- ------ 46.1/55.4 MB 10.8 MB/s eta 0:00:01
   --------------------------------- ------ 46.9/55.4 MB 7.9 MB/s eta 0:00:02
   ----------------------------------- ---- 48.5/55.4 MB 7.8 MB/s eta 0:00:01
   ------------------------------------ --- 51.1/55.4 MB 8.0 MB/s eta 0:00:01
   -------------------------------------- - 53.5/55.4 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------  55.3/55.4 MB 8.2 MB/s eta 0:00:01
   ---------------------------------------- 55.4/55.4 MB 8.1 MB/s  0:00:07
Downloading torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
   ---------------------------------------- 0.0/114.6 MB ? eta -:--:--
    --------------------------------------- 2.6/114.6 MB 13.1 MB/s eta 0:00:09
   - -------------------------------------- 5.2/114.6 MB 12.6 MB/s eta 0:00:09
   -- ------------------------------------- 7.9/114.6 MB 12.6 MB/s eta 0:00:09
   --- ------------------------------------ 10.5/114.6 MB 12.7 MB/s eta 0:00:09
   ---- ----------------------------------- 13.1/114.6 MB 12.7 MB/s eta 0:00:09
   ----- ---------------------------------- 15.7/114.6 MB 12.6 MB/s eta 0:00:08
   ------ --------------------------------- 18.4/114.6 MB 12.6 MB/s eta 0:00:08
   ------- -------------------------------- 20.7/114.6 MB 12.4 MB/s eta 0:00:08
   -------- ------------------------------- 23.3/114.6 MB 12.4 MB/s eta 0:00:08
   -------- ------------------------------- 25.4/114.6 MB 12.2 MB/s eta 0:00:08
   --------- ------------------------------ 28.0/114.6 MB 12.2 MB/s eta 0:00:08
   ---------- ----------------------------- 30.4/114.6 MB 12.2 MB/s eta 0:00:07
   ----------- ---------------------------- 32.8/114.6 MB 12.1 MB/s eta 0:00:07
   ----------- ---------------------------- 33.8/114.6 MB 11.6 MB/s eta 0:00:07
   ------------ --------------------------- 36.4/114.6 MB 11.7 MB/s eta 0:00:07
   ------------- -------------------------- 39.1/114.6 MB 11.8 MB/s eta 0:00:07
   -------------- ------------------------- 40.4/114.6 MB 11.4 MB/s eta 0:00:07
   -------------- ------------------------- 40.6/114.6 MB 11.0 MB/s eta 0:00:07
   -------------- ------------------------- 41.9/114.6 MB 10.6 MB/s eta 0:00:07
   --------------- ------------------------ 43.0/114.6 MB 10.3 MB/s eta 0:00:07
   --------------- ------------------------ 44.0/114.6 MB 10.1 MB/s eta 0:00:08
   ---------------- ----------------------- 46.1/114.6 MB 10.1 MB/s eta 0:00:07
   ---------------- ----------------------- 47.7/114.6 MB 10.0 MB/s eta 0:00:07
   ----------------- ---------------------- 49.0/114.6 MB 9.8 MB/s eta 0:00:07
   ----------------- ---------------------- 50.1/114.6 MB 9.6 MB/s eta 0:00:07
   ----------------- ---------------------- 51.4/114.6 MB 9.5 MB/s eta 0:00:07
   ------------------ --------------------- 52.4/114.6 MB 9.3 MB/s eta 0:00:07
   ------------------ --------------------- 53.5/114.6 MB 9.2 MB/s eta 0:00:07
   ------------------- -------------------- 54.5/114.6 MB 9.0 MB/s eta 0:00:07
   ------------------- -------------------- 55.8/114.6 MB 8.9 MB/s eta 0:00:07
   ------------------- -------------------- 56.9/114.6 MB 8.8 MB/s eta 0:00:07
   -------------------- ------------------- 58.2/114.6 MB 8.7 MB/s eta 0:00:07
   -------------------- ------------------- 59.2/114.6 MB 8.6 MB/s eta 0:00:07
   --------------------- ------------------ 61.3/114.6 MB 8.6 MB/s eta 0:00:07
   ---------------------- ----------------- 64.0/114.6 MB 8.7 MB/s eta 0:00:06
   ----------------------- ---------------- 66.1/114.6 MB 8.8 MB/s eta 0:00:06
   ------------------------ --------------- 68.9/114.6 MB 8.9 MB/s eta 0:00:06
   ------------------------ --------------- 71.3/114.6 MB 9.0 MB/s eta 0:00:05
   ------------------------- -------------- 74.2/114.6 MB 9.1 MB/s eta 0:00:05
   -------------------------- ------------- 76.8/114.6 MB 9.2 MB/s eta 0:00:05
   --------------------------- ------------ 79.4/114.6 MB 9.3 MB/s eta 0:00:04
   ---------------------------- ----------- 82.1/114.6 MB 9.3 MB/s eta 0:00:04
   ----------------------------- ---------- 84.4/114.6 MB 9.4 MB/s eta 0:00:04
   ------------------------------ --------- 86.0/114.6 MB 9.4 MB/s eta 0:00:04
   ------------------------------ --------- 88.1/114.6 MB 9.4 MB/s eta 0:00:03
   ------------------------------- -------- 90.7/114.6 MB 9.4 MB/s eta 0:00:03
   -------------------------------- ------- 93.3/114.6 MB 9.5 MB/s eta 0:00:03
   --------------------------------- ------ 94.6/114.6 MB 9.5 MB/s eta 0:00:03
   --------------------------------- ------ 95.4/114.6 MB 9.3 MB/s eta 0:00:03
   --------------------------------- ------ 95.7/114.6 MB 9.3 MB/s eta 0:00:03
   --------------------------------- ------ 95.7/114.6 MB 9.3 MB/s eta 0:00:03
   --------------------------------- ------ 96.2/114.6 MB 8.8 MB/s eta 0:00:03
   --------------------------------- ------ 96.7/114.6 MB 8.7 MB/s eta 0:00:03
   ---------------------------------- ----- 97.8/114.6 MB 8.7 MB/s eta 0:00:02
   ---------------------------------- ----- 99.6/114.6 MB 8.7 MB/s eta 0:00:02
   ----------------------------------- ---- 101.7/114.6 MB 8.7 MB/s eta 0:00:02
   ------------------------------------ --- 103.3/114.6 MB 8.7 MB/s eta 0:00:02
   ------------------------------------ --- 104.1/114.6 MB 8.6 MB/s eta 0:00:02
   ------------------------------------- -- 106.2/114.6 MB 8.6 MB/s eta 0:00:01
   ------------------------------------- -- 107.2/114.6 MB 8.5 MB/s eta 0:00:01
   ------------------------------------- -- 108.8/114.6 MB 8.5 MB/s eta 0:00:01
   -------------------------------------- - 110.4/114.6 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------  112.5/114.6 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------  114.3/114.6 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------- 114.6/114.6 MB 8.4 MB/s  0:00:13
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 1.1/1.1 MB 9.4 MB/s  0:00:00
Downloading accelerate-1.13.0-py3-none-any.whl (383 kB)
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   -------- ------------------------------- 2.1/10.2 MB 10.1 MB/s eta 0:00:01
   --------------- ------------------------ 3.9/10.2 MB 9.5 MB/s eta 0:00:01
   ------------------------ --------------- 6.3/10.2 MB 9.9 MB/s eta 0:00:01
   --------------------------------- ------ 8.7/10.2 MB 10.3 MB/s eta 0:00:01
   ---------------------------------------- 10.2/10.2 MB 9.8 MB/s  0:00:01
Downloading huggingface_hub-1.9.0-py3-none-any.whl (637 kB)
   ---------------------------------------- 0.0/637.4 kB ? eta -:--:--
   ---------------------------------------- 637.4/637.4 kB 7.2 MB/s  0:00:00
Downloading hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ---------------------- ----------------- 2.1/3.7 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 10.2 MB/s  0:00:00
Downloading httpx-0.28.1-py3-none-any.whl (73 kB)
Downloading httpcore-1.0.9-py3-none-any.whl (78 kB)
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------- ----- 2.4/2.7 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 9.9 MB/s  0:00:00
Downloading datasets-4.8.4-py3-none-any.whl (526 kB)
   ---------------------------------------- 0.0/527.0 kB ? eta -:--:--
   ---------------------------------------- 527.0/527.0 kB 7.7 MB/s  0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading fsspec-2026.2.0-py3-none-any.whl (202 kB)
Downloading multiprocess-0.70.19-py313-none-any.whl (156 kB)
Downloading peft-0.18.1-py3-none-any.whl (556 kB)
   ---------------------------------------- 0.0/557.0 kB ? eta -:--:--
   ---------------------------------------- 557.0/557.0 kB 7.1 MB/s  0:00:00
Downloading aiohttp-3.13.5-cp313-cp313-win_amd64.whl (458 kB)
Using cached multidict-6.7.1-cp313-cp313-win_amd64.whl (45 kB)
Using cached yarl-1.23.0-cp313-cp313-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading filelock-3.25.2-py3-none-any.whl (26 kB)
Using cached frozenlist-1.8.0-cp313-cp313-win_amd64.whl (43 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 2.1/2.1 MB 10.7 MB/s  0:00:00
Downloading numpy-2.4.4-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.3 MB 11.4 MB/s eta 0:00:01
   --------------- ------------------------ 4.7/12.3 MB 11.5 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.3 MB 11.8 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 11.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 10.2 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 9.1 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 9.1 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 9.1 MB/s eta 0:00:01

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!pip install gdown

Collecting gdown
  Downloading gdown-5.2.1-py3-none-any.whl.metadata (5.8 kB)
Collecting beautifulsoup4 (from gdown)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: filelock in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from gdown) (3.25.2)
Requirement already satisfied: requests[socks] in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from gdown) (2.33.1)
Requirement already satisfied: tqdm in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from gdown) (4.67.3)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->gdown)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from requests[socks]->gdown) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from requests[socks]->gdown) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from requests[socks]->gdown) (2026.2.25)
Collecting PySocks!=1.5.7,>=1.5.6 (from requests[socks]->gdown)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: colorama in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from tqdm->gdown) (0.4.6)
Downloading gdown-5.2.1-py3-none-any.whl (18 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Installing collected packages: soupsieve, PySocks, beautifulsoup4, gdown

   ------------------------------ --------- 3/4 [gdown]
   ---------------------------------------- 4/4 [gdown]

Successfully installed PySocks-1.7.1 beautifulsoup4-4.14.3 gdown-5.2.1 soupsieve-2.8.3

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Обучение маленьких моделей

In [ ]:
from manim_finetune.utils import data_utils
from manim_finetune import constants
from manim_finetune.utils import model_utils
from manim_finetune.utils import archive_utils

Загружаем [данные](https://drive.google.com/file/d/1gb8S-8xharo5YYTOczAB_6YdOiQR_YCj/view?usp=drive_link):

In [ ]:
data_filename = "english_data.csv"
data_utils.download_data(constants.DATASET_DRIVE_ID, data_filename)
data = data_utils.load_data(data_filename)

Загружаем начальную модель, которую будем обучать (в нашем случае Qwen2.5-Coder-3B-Instruct)

In [ ]:
from transformers import BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_enable_fp32_cpu_offload=True,
)

In [ ]:
default_tokenizer, default_model = model_utils.load_model_and_tokenizer(
    constants.MODEL_NAME,
    bnb_config
)

Работаем с данными:

In [ ]:
train_dataset, test_dataset = data_utils.create_datasets(
    data,
    default_tokenizer,
    constants.TEST_SIZE,
    constants.MAX_LENGTH
)

Настраиваем модель:

In [ ]:
model = model_utils.apply_lora(
    default_model,
    constants.LORA_R,
    constants.LORA_ALPHA
)

In [ ]:
from trl import SFTConfig
import torch

torch.cuda.empty_cache()

training_args = SFTConfig(
    bf16=False,
    fp16=False,

    output_dir=constants.OUTPUT_DIR,
    num_train_epochs=constants.EPOCHS,
    per_device_train_batch_size=constants.BATCH_SIZE,
    gradient_accumulation_steps=constants.GRAD_ACCUM_STEPS,
    learning_rate=constants.LEARNING_RATE,

    dataset_text_field="text",

    eval_strategy="steps",
    eval_steps=50,
    logging_steps=50,
    save_steps=250,
    save_total_limit=5,

    per_device_eval_batch_size=1,
    eval_accumulation_steps=1,
    prediction_loss_only=True,

    max_length=constants.MAX_LENGTH
)

In [ ]:
trainer = model_utils.create_trainer(model, default_tokenizer, train_dataset, test_dataset, training_args)

Обучаем:

In [ ]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

TrainOutput(global_step=644, training_loss=0.5607716607751313, metrics={'train_runtime': 9000.1497, 'train_samples_per_second': 0.568, 'train_steps_per_second': 0.072, 'total_flos': 2.208213464174592e+16, 'train_loss': 0.5607716607751313})

Сохраняем дообученную модель:

In [ ]:
model_utils.save_model(trainer, constants.SAVE_MODEL_PATH)

In [ ]:
from manim_finetune.utils import archive_utils

archive_utils.make_zip(constants.SAVE_MODEL_PATH, constants.ZIP_NAME + ".zip")

# Оцениваем крутость модели

In [10]:
from manim_finetune.utils import archive_utils
from manim_finetune.utils import eval_utils
from manim_finetune import constants
from manim_finetune.utils import data_utils

Загружаем [модель](https://drive.google.com/file/d/1TgsqiUSQ6k_Wuw0LR2On1r5j765DeHgZ/view?usp=drive_link):

In [ ]:
tune_model_filename = constants.ZIP_NAME + ".zip"
data_utils.download_data(constants.TUNE_MODEL_DRIVE_ID, tune_model_filename)
archive_utils.extract_zip(tune_model_filename, constants.SAVE_MODEL_PATH)

Downloading...
From: https://drive.google.com/uc?id=1TgsqiUSQ6k_Wuw0LR2On1r5j765DeHgZ&confirm=t
To: c:\Users\User\Documents\Python Projects\Prompt2Scene\tune_model_english_qwen_coder.zip
100%|██████████| 7.28M/7.28M [00:05<00:00, 1.36MB/s]

In [ ]:
test_tokenizer, test_model = model_utils.load_model_and_tokenizer(constants.SAVE_MODEL_PATH)

Скачиваем данные:

In [ ]:
data_filename = "english_data.csv"
data_utils.download_data(constants.DATASET_DRIVE_ID, data_filename)
data = data_utils.load_data(data_filename)

Устанавливаем библиотеки для работы с manim:

In [ ]:
!sudo apt update
!sudo apt install libcairo2-dev \
    texlive texlive-latex-extra texlive-fonts-extra \
    texlive-latex-recommended texlive-science \
    tipa libpango1.0-dev
!pip install manim
!pip install IPython==8.21.0

Hit:1 https://cli.github.com/packages stable InRelease
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
132 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libcairo2-dev is already the newest version (1.16.0-5ubuntu2).
texlive is already the newest version (2021.20220204-1).
texlive-fonts-extra is already the newest version (2021.20220204-1).
texlive-latex-extra is already the newest version (2021.20220204-1).
texlive-latex-recommended is already the newest version (2021.20220204-1).
texlive-science is already the newest version (2021.20220204-1).
tipa is already the newest version (2:1.3-21).
libpango1.0-dev is already the newest version (1.50.6+ds-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 132 not upgraded.
Requirement already satisfied: manim in /usr/local/lib/python3.12/dist-packages (0.20.1)
Requirement already satisfied: av>=15.0 in /usr/local/lib/python3.12/dist-packages (from manim) (17.0.0)
Requirement already satisfied: beautifulsoup4>=4.12 in /usr/local/lib/python3.12/dist-packages (from manim) (4.13.5)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.12/dist-packages (from manim) (8.3.1)
Requirement already satisfied: cloup>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from manim) (3.0.8)
Requirement already satisfied: decorator>=4.3.2 in /usr/local/lib/python3.12/dist-packages (from manim) (4.4.2)
Requirement already satisfied: isosurfaces>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from manim) (0.1.2)
Requirement already satisfied: manimpango<1.0.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from manim) (0.6.1)
Requirement already satisfied: mapbox-earcut>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from manim) (2.0.0)
Requirement already satisfied: moderngl-window>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from manim) (3.1.1)
Requirement already satisfied: moderngl<6.0.0,>=5.7.0 in /usr/local/lib/python3.12/dist-packages (from manim) (5.12.0)
Requirement already satisfied: networkx>=2.6 in /usr/local/lib/python3.12/dist-packages (from manim) (3.6.1)
Requirement already satisfied: numpy>=2.1 in /usr/local/lib/python3.12/dist-packages (from manim) (2.4.3)
Requirement already satisfied: pillow>=11.0 in /usr/local/lib/python3.12/dist-packages (from manim) (11.3.0)
Requirement already satisfied: pycairo<2.0.0,>=1.14 in /usr/local/lib/python3.12/dist-packages (from manim) (1.29.0)
Requirement already satisfied: pydub>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from manim) (0.25.1)
Requirement already satisfied: pygments>=2.17 in /usr/local/lib/python3.12/dist-packages (from manim) (2.19.2)
Requirement already satisfied: rich>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from manim) (13.9.4)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from manim) (1.16.3)
Requirement already satisfied: screeninfo>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from manim) (0.8.1)
Requirement already satisfied: skia-pathops>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from manim) (0.9.2)
Requirement already satisfied: srt>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from manim) (3.5.3)
Requirement already satisfied: svgelements>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from manim) (1.9.6)
Requirement already satisfied: tqdm>=4.21.0 in /usr/local/lib/python3.12/dist-packages (from manim) (4.67.3)
Requirement already satisfied: typing-extensions>=4.12.0 in /usr/local/lib/python3.12/dist-packages (from manim) (4.15.0)
Requirement already satisfied: watchdog>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from manim) (6.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.12->manim) (2.8.3)
Requirement already satisfied: glcontext>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from moderngl<6.0.0,>=5.7.0->manim) (3.0.0)
Requirement already satisfied: pyglet>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from moderngl-window>=2.0.0->manim) (2.1.13)
Requirement already satisfied: pyglm<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from moderngl-window>=2.0.0->manim) (2.8.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.0.0->manim) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.0.0->manim) (0.1.2)
Requirement already satisfied: IPython==8.21.0 in /usr/local/lib/python3.12/dist-packages (8.21.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from IPython==8.21.0) (4.4.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from IPython==8.21.0) (0.19.2)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from IPython==8.21.0) (0.2.1)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /usr/local/lib/python3.12/dist-packages (from IPython==8.21.0) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from IPython==8.21.0) (2.19.2)
Requirement already satisfied: stack-data in /usr/local/lib/python3.12/dist-packages (from IPython==8.21.0) (0.6.3)
Requirement already satisfied: traitlets>=5 in /usr/local/lib/python3.12/dist-packages (from IPython==8.21.0) (5.7.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from IPython==8.21.0) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->IPython==8.21.0) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->IPython==8.21.0) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit<3.1.0,>=3.0.41->IPython==8.21.0) (0.6.0)
Requirement already satisfied: executing>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from stack-data->IPython==8.21.0) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from stack-data->IPython==8.21.0) (3.0.1)
Requirement already satisfied: pure-eval in /usr/local/lib/python3.12/dist-packages (from stack-data->IPython==8.21.0) (0.2.3)

In [ ]:
from manim_finetune.utils import gemini_utils
from manim_finetune import config

gemini_client = gemini_utils.get_gemini(config.GEMINI_API_KEY)

In [ ]:
from manim_finetune.utils import eval_utils
from manim_finetune.utils import manim_test_utils
from manim_finetune.utils import gemini_utils
from tqdm import tqdm

NUM_SAMPLES = 120
sample_df = data.sample(n=NUM_SAMPLES)

failed = list()
scores = dict()

for idx, row in tqdm(sample_df.iterrows(), total=NUM_SAMPLES):
    prompt = row['prompt']
    code = eval_utils.run_inference(test_model, test_tokenizer, prompt, constants.TEMPERATURE)
    if manim_test_utils.manim_test(code, idx=idx):
        score = gemini_utils.evaluate_code_with_gemini(gemini_client, prompt, code, constants.GEMINI_MODEL)
    else:
        score = 0
        failed.append(idx)
    scores[idx] = score

In [ ]:
print(f"Среднее (с учетом неудачных запусков): {sum(scores.values()) / len(scores)}")
print(f"Среднее (без учета неудачных запусков): {sum(scores.values()) / (len(scores) - len(failed))}")
print(f"Число неудачных запусков: {len(failed)}")
print(f"Неудачные запуски: {', '.join(failed)}")

# Обучение с подкреплением

In [6]:
!pip install google-genai

Requirement already satisfied: google-genai in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (1.73.1)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.48.1 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.49.2)
Requirement already satisfied: httpx<1.0.0,>=0.28.1 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (0.28.1)
Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (2.13.3)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (2.33.1)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (16.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.14.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (4.15.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (1.9.0)
Requirement already satisfied: sniffio in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-genai) (1.3.1)
Requirement already satisfied: idna>=2.8 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from anyio<5.0.0,>=4.8.0->google-genai) (3.11)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (46.0.7)
Requirement already satisfied: certifi in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from httpx<1.0.0,>=0.28.1->google-genai) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.28.1->google-genai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.3 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (2.46.3)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from pydantic<3.0.0,>=2.9.0->google-genai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from requests<3.0.0,>=2.28.1->google-genai) (2.6.3)
Requirement already satisfied: cffi>=2.0.0 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (2.0.0)
Requirement already satisfied: pycparser in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\user\documents\python projects\prompt2scene\.venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.48.1->google-auth[requests]<3.0.0,>=2.48.1->google-genai) (0.6.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
from manim_finetune.utils import gemini_utils
from manim_finetune import config

gemini_client = gemini_utils.get_gemini(config.GEMINI_API_KEY)

Загружаем модель из архива:

In [11]:
from manim_finetune import constants
from manim_finetune.utils import data_utils
from manim_finetune.utils import archive_utils

tune_model_filename = constants.ZIP_NAME + ".zip"
data_utils.download_data(constants.TUNE_MODEL_DRIVE_ID, tune_model_filename)
archive_utils.extract_zip(tune_model_filename, constants.SAVE_MODEL_PATH)

Downloading...
From: https://drive.google.com/uc?id=1TgsqiUSQ6k_Wuw0LR2On1r5j765DeHgZ&confirm=t
To: c:\Users\User\Documents\Python Projects\Prompt2Scene\tune_model_english_qwen_coder.zip
100%|██████████| 7.28M/7.28M [00:01<00:00, 3.80MB/s]

In [ ]:
test_tokenizer, test_model = model_utils.load_model_and_tokenizer(constants.SAVE_MODEL_PATH, False)

Скачиваем данные:

In [ ]:
from manim_finetune.utils import data_utils

data_filename = "english_data.csv"
data_utils.download_data(constants.DATASET_DRIVE_ID, data_filename)
data = data_utils.load_data(data_filename)

Генерируем пары "плохой-хороший" код для последующего обучения с подкреплением. В качестве судьи для оченки кода мы использовали `Gemma` (это оправдано тем, что у этих моделей щедрые ограничения)

In [ ]:
from manim_finetune.utils import rl_utils
from tqdm import tqdm

NUM_SAMPLES = 120
CANDIDATES_PER_PROMPT = 5

dpo_data = []

sample_df = data.sample(n=NUM_SAMPLES)

for idx, row in tqdm(sample_df.iterrows(), total=NUM_SAMPLES):
    prompt = row['prompt']
    pair = rl_utils.process_step(
        prompt,
        test_model,
        test_tokenizer,
        gemini_client,
        CANDIDATES_PER_PROMPT,
        constants.TEMPERATURE
    )
    if pair is not None:
        dpo_data.append(pair)

print(f"Collected {len(dpo_data)} pairs for DPO")

Сохраняем полученные пары в .csv файл:

In [ ]:
import pandas as pd
from manim_finetune.utils import data_utils
from manim_finetune import constants

dpo_dataset = pd.DataFrame(dpo_data)
data_utils.save_dataset(dpo_dataset, "dpo_preferences.csv")

Из-за технических ограничений нам пришлось перезапускать код выше несколько раз, для генерации хоть какого-то приличного количества пар. Все полученные датасеты (если Вам вдруг интересно) можно посмотреть на [Google Диске](https://drive.google.com/drive/folders/1s5zS-Hfu3quRkUKjJ4VMvCD8etfNNpBg?usp=drive_link).

Ниже загружается [датасет](https://drive.google.com/file/d/1QfRb-1mLdppG1zOpNpzgSiue3jV3xl22/view?usp=drive_link), который получен объединением всех датасетов из папки, которая была упомянута выше.

In [ ]:
from manim_finetune.utils import data_utils
from manim_finetune import constants

dpo_filename = "all_dpo_preferences.csv"
data_utils.download_data(constants.DPO_DATASET_DRIVE_ID, dpo_filename)
dpo_preferences = data_utils.load_data(dpo_filename)

c:\Users\User\Documents\Python Projects\Prompt2Scene\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading...
From: https://drive.google.com/uc?id=1QfRb-1mLdppG1zOpNpzgSiue3jV3xl22&confirm=t
To: c:\Users\User\Documents\Python Projects\Prompt2Scene\dpo_preferences.csv
100%|██████████| 159k/159k [00:00<00:00, 2.36MB/s]

In [ ]:
from datasets import Dataset

# dpo_preferences = dpo_preferences[dpo_preferences["rejected_score"] == -1]
dpo_dataset = Dataset.from_pandas(dpo_preferences[["prompt", "chosen", "rejected"]])

Теперь дообучим модель на собранных парах:

In [ ]:
from transformers import BitsAndBytesConfig

dpo_bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
)

In [ ]:
dpo_tokenizer, dpo_model = model_utils.load_model_and_tokenizer(constants.SAVE_MODEL_PATH, dpo_bnb_config)

In [ ]:
if dpo_tokenizer.pad_token is None:
    dpo_tokenizer.pad_token = dpo_tokenizer.eos_token

In [ ]:
from peft import prepare_model_for_kbit_training

dpo_model = prepare_model_for_kbit_training(dpo_model)
dpo_model.gradient_checkpointing_enable()

In [ ]:
from manim_finetune.utils import model_utils

dpo_model = model_utils.apply_lora(
    dpo_model,
    constants.DPO_LORA_R,
    constants.DPO_LORA_ALPHA,
    ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
)

In [ ]:
dpo_dataset = dpo_dataset.map(lambda example: rl_utils.format_dpo_string(example, dpo_tokenizer))

In [ ]:
from trl import DPOConfig

dpo_training_args = DPOConfig(
    output_dir=constants.DPO_OUTPUT_DIR,
    num_train_epochs=constants.DPO_EPOCHS,
    per_device_train_batch_size=constants.DPO_BATCH_SIZE,
    gradient_accumulation_steps=constants.DPO_GRAD_ACCUM_STEPS,
    learning_rate=constants.DPO_LEARNING_RATE,
    beta=constants.DPO_BETA,
    logging_steps=10,
    save_steps=100,
    save_total_limit=3,
    bf16=False,
    fp16=False,
    gradient_checkpointing=True,
    remove_unused_columns=False,
    max_length=constants.DPO_MAX_LENGTH,
    report_to="none"
)

In [ ]:
dpo_trainer = rl_utils.create_dpo_trainer(
    dpo_model,
    dpo_tokenizer,
    dpo_training_args,
    dpo_dataset
)

In [ ]:
dpo_trainer.train()

Сохраняем модель:

In [ ]:
model_utils.save_model(dpo_trainer, constants.DPO_SAVE_MODEL_PATH)

In [ ]:
from manim_finetune.utils import archive_utils

archive_utils.make_zip(constants.SAVE_MODEL_PATH, constants.DPO_ZIP_NAME + ".zip")

# Оценка качества обучения с подкреплением

In [ ]:
# TODO: Загрузка модели и данных

In [ ]:
!sudo apt update
!sudo apt install libcairo2-dev \
    texlive texlive-latex-extra texlive-fonts-extra \
    texlive-latex-recommended texlive-science \
    tipa libpango1.0-dev
!pip install manim
!pip install IPython==8.21.0

In [ ]:
from manim_finetune.utils import gemini_utils
from manim_finetune import config

gemini_client = gemini_utils.get_gemini(config.GEMINI_API_KEY)

In [ ]:
from manim_finetune.utils import eval_utils
from manim_finetune.utils import manim_test_utils
from manim_finetune.utils import gemini_utils
from tqdm import tqdm

NUM_SAMPLES = 120
sample_df = data.sample(n=NUM_SAMPLES)

failed = list()
scores = dict()

for idx, row in tqdm(sample_df.iterrows(), total=NUM_SAMPLES):
    prompt = row['prompt']
    code = eval_utils.run_inference(test_model, test_tokenizer, prompt, constants.TEMPERATURE)
    if manim_test_utils.manim_test(code, idx=idx):
        score = gemini_utils.evaluate_code_with_gemini(gemini_client, prompt, code, constants.GEMINI_MODEL)
    else:
        score = 0
        failed.append(idx)
    scores[idx] = score

In [ ]:
print(f"Среднее (с учетом неудачных запусков): {sum(scores.values()) / len(scores)}")
print(f"Среднее (без учета неудачных запусков): {sum(scores.values()) / (len(scores) - len(failed))}")
print(f"Число неудачных запусков: {len(failed)}")
print(f"Неудачные запуски: {', '.join(failed)}")